### ISSUE TITLE
add travis ci for movealarm server ( spring boot project)

### ISSUE THREAD

**Issue by whitemalt** [whitemalt/Move-Alarm_ORCA#2]

**Comment by angelobms** [comment]
Add travis ci to movealarm server. #3

**Comment by whitemalt** [comment]
seem travis-ci not detect file

**Comment by angelobms** [comment]
In order for your application as a repository in git to be detected it is necessary to create the .yam file according to the travis-ci documentation in the project root folder. Add the file in Move-Alarm_ORCA instead of add in movealarm server.

**Comment by whitemalt** [comment]
I don't mind where travis-ci.yml file locate. Thx for advise.

**Comment by whitemalt** [comment]
solved

**Comment by whitemalt** [comment]
solved
